apiVersion: v2
name: krateo-crds
description: Krateo PlatformOps CRDs
type: application
icon: "https://github.com/projectkerberus/kerberus-dashboard/blob/main/docs/media/square_black_logo.png"

version: VERSION
appVersion: VERSION