apiVersion: templates.krateo.io/v1alpha1
kind: Template
metadata:
  name: krateo-template-awsstack
spec:
  owner: STRING
  tags: ["ddd", "eee", "fff"]
  title: Deployment title
  widgets:
    - title: AWS Stack - EKS details
      description: EKS cluster name and network name.
      properties:
        - type: box
          style: info
          value: EKS cluster name and network name.
        - title: Rds Disk Size
          type: number
          required: true
          key: rdsDataDiskSizeGb
          description: The size of the RDS disk
          default: "10"
    - title: Database
      description: Please specify the database name, region, storage type, instance class and engine version.
      properties:
        - type: box
          style: warning
          value: Please specify the database name, region, storage type, instance class and engine version.
        - title: Rds Instance Class
          type: radio
          required: true
          key: rdsInstanceClass
          description: The instance class of the RDS
          default: db.t3.micro
          values:
            - title: db.t3.micro
              value: db.t3.micro
              description: 1 core\n2 vCPU\n1 GB of memory
              cost: "10"
            - title: db.t3.medium
              value: db.t3.medium
              description: 1 core\n2 vCPU\n2 GB of memory
              cost: "20"
            - title: db.t3.large
              value: db.t3.large
              description: 2 core\n2 vCPU\n8 GB of memory
              cost: "30"
