name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
     
      - name: Set tag
        run: echo "::set-output name=VERSION_TAG::$(git describe --always --tags | sed 's/-/./2' | sed 's/-/./2' )"
        id: tagger

      - name: Replace Version in Chart.yaml
        run: sed -i 's/VERSION/${{ steps.tagger.outputs.VERSION_TAG }}/g' ./chart/Chart.yaml

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18' # The Go version to download (if necessary) and use.
  
      - run: go generate ./...

      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.HELM_CHARTS_BOT }}
          charts_dir: ./
          charts_url: https://charts.krateo.io
          owner: krateoplatformops
          repository: helm-charts
          branch: gh-pages